apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: alpine
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
  - name: shipa
    image: shipasoftware/cli:v1.3.1-cloud
    command:
    - cat
    tty: true
    volumeMounts:
    - name: shipa-token
      mountPath: /root/.shipa
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: shipa-token
    secret:
      secretName: shipa-token
